### PR TITLE
Add a method to get rendered components

### PR DESCRIPTION
**Pull request by koko-ng**
Hi,
I thought it would be useful to be able to get the rendered component, so we can call the methods of a component once it is rendered.
Yet I used the numerical index, but I think it would be useful to switch to a dictionary structure for the constructor of DOMRegistery rather than an array.

Btw: Thanks for this project, it is very useful for projects partially built with react.

### CODE REVIEW

**Comment by auniverseaway** [comment]
@koko-ng Sorry for the late response. I'll get dictionary support added. I've made some significant changes that makes this PR a bit obsolete... I'm going to leave it open for now and I'll let you know when dictionary support ships... it should be very soon.

**Comment by koko-ng** [comment]
Nice to hear from you, I'm looking forward to see this update.

Le 16 mai 2018 02:37:13 GMT+02:00, Chris Millar <notifications@github.com> a écrit :
>@koko-ng Sorry for the late response. I'll get dictionary support
>added. I've made some significant changes that makes this PR a bit
>obsolete... I'm going to leave it open for now and I'll let you know
>when dictionary support ships... it should be very soon.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/auniverseaway/react-dom-components/pull/2#issuecomment-389357863

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by auniverseaway** [comment]
@koko-ng I'm happy to report `domRegistery.components` is dictionary based.

If you have a DOM Component called `myComponent` you can access it by...

`domRegistery.components['myComponent']` to get the model, react component, etc.

Note, there was a pretty significant API change in releasing 1.0.X so you may have to change some things around with your impl. The notes are in README howto.

**Comment by koko-ng** [comment]
Wow, impressive update. I will try to look at it soon. 
Thanks

**Pull request closed without merging**
